### ISSUE TITLE
Issue starting tor service

### ISSUE THREAD

**Issue by TheGodRX** [Anish-M-code/onionize#1]
2023/03/25 00:30:43 [emerg] 21649#21649: unknown directive "subs_filter_types" in /home/severx/onionize/eotk/projects.d/tor_server.d/nginx.conf:118

**Comment by TheGodRX** [comment]
I believe this error is because in the nginx conf file it creates it says subs_filter instead of sub_filter and it rewrite the conf everytime the script is run so even if I edit the conf file and try to run onionze.py again it erases my conf edits and uses subs_filter

**Comment by Anish-M-code** [comment]
@codercoins onionize.py was actually supposed to run only once , it just installs Enterprise onion toolkit and helps in automating creation of onion service for clearnet domains only once i used this https://github.com/alecmuffett/eotk/blob/master/docs.d/HOW-TO-INSTALL.md as reference for automation. If onionize is run again it would overwrite every stuff installed previously.

**Comment by TheGodRX** [comment]
Lol yes that makes sense I figured that out yesterday, thank you for your
prompt response!
I am working on a new project and would like  to know if you are interested
in collaborating together perhaps if the project interests you..
The project is for tor but it needs to be a bit hush hush atm as I don't
want the code getting out just yet so we would have to work over tox or
DarkMX to make sure things stay quiet until we release the code.
If you are interested let me know and I will create a chat link where we
can talk securely over tor or i2p.
